server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AdrianCAmes/nttdata-bootcamp-config-data
          searchPaths: project-1
          default-label: main
  security:
    user:
      name: root
      password: p1a2s3s